[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "coch"
dynamic = ["version"]
dependencies = [
  "numpy",
  "Pillow",
  "matplotlib",
  "chess",
]